version: "3"
services:
  springboot:
    image: twoosky/docker-springboot
    mem_limit: 128m
    volumes:
      - ./:/app
#    environment:
#      - MYSQL_HOST=docker-springboot-mysql.cgztrz6ixthx.ap-northeast-2.rds.amazonaws.com
#      - MYSQL_USER=root
#      - MYSQL_ROOT_PASSWORD=dlgksmf4051
#      - MYSQL_DATABASE=myapp
#      - MYSQL_PORT=3306
    env_file:
      - .env
    ports:
      - "80:8080"

#  nginx:
#    restart: always
#    image: twoosky/docker-nginx
#    mem_limit: 128m
#    ports:
#      - "80:80"
#    links:
#      - springboot