version: "3"
services:
  springboot:
    image: twoosky/docker-springboot
    mem_limit: 128m
    environment:
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_USER: $MYSQL_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_PORT: $MYSQL_PORT

  nginx:
    restart: always
    image: twoosky/docker-nginx
    ports:
      - "80:80"
    depends_on:
      - springboot