version: "3"
services:
  springboot:
    image: twoosky/docker-springboot
    mem_limit: 128m
    volumes:
      - ./:/app
    env_file:
      - .env

  nginx:
    restart: always
    image: twoosky/docker-nginx
    ports:
      - "80:80"
    depends_on:
      - springboot