version: "3"
services:
        redis:
                image: redis:alpine
                command: redis-server --port 6379
                container_name: redis_boot
                hostname: redis_boot
                ports:
                        - 6379:6379
