version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  springboot:
    build: .
    environment:
      - SPRING_DATA_REDIS_HOST=redis
    ports:
      - "8080:8080"
    depends_on:
      - redis
