spring:
  datasource:
    url: jdbc:mysql://docker-springboot-mysql.cgztrz6ixthx.ap-northeast-2.rds.amazonaws.com:3306/myapp?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: dlgksmf4051
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
