spring:
  datasource:
    url: jdbc:mysql://mysql:3306/myapp?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: dlgksmf4051
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
