spring:
    datasource:
        url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?serverTimezone=UTC&characterEncoding=UTF-8
        username: ${rds.username}
        password: ${rds.password}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL57Dialect


#spring:
#    datasource:
#        url: jdbc:mysql://database-demo.cgztrz6ixthx.ap-northeast-2.rds.amazonaws.com:3306/myapp?serverTimezone=UTC&characterEncoding=UTF-8
#        username: admin
#        password: dlgksmf4051
#        driver-class-name: com.mysql.cj.jdbc.Driver
